# index:
#    path: /home
#    controller: App\Controller\HomeController::index
# homepage:
#    path: /home
#    controller: App\Controller\HomeController::home
app_logout:
    path: /logout
    methods: GET
